[[chapter2]]
== Arithmetic Instructions

=== BCD Add

Synopsis::
Computes the BCD sum of the values in registers _rs1_ and _rs2_ and places the result in register _rd_.

Mnemonic::
====
addbcd _rd_, _rs1_, _rs2_

addbcdw _rd_, _rs1_, _rs2_

====
Encoding::
TBD, somewhere in OP/OP64

Description::

Computes the BCD sum of the values in registers _rs1_ and _rs2_ and places the result in register _rd_.
If either source operand is invalid, or the sum overflows, the canonical invalid BCD value (0x0) is placed in register _rd_.
The word-sized version is RV64 only.

SAIL code::
[source,sail]
--
TODO
--

=== BCD Subtract

Synopsis::
Computes the BCD difference of the values in registers _rs1_ and _rs2_ and places the result in register _rd_.

Mnemonic::
====
subbcd _rd_, _rs1_, _rs2_

subbcdw _rd_, _rs1_, _rs2_

====
Encoding::
TBD, somewhere in OP/OP64

Description::

Computes the BCD difference of the values in registers _rs1_ and _rs2_ and places the result in register _rd_.
If either source operand is invalid, or the difference overflows, the canonical invalid BCD value (0x0) is placed in register _rd_.
The word-sized version is RV64 only.

SAIL code::
[source,sail]
--
TODO
--

=== BCD Multiply

Synopsis::
Computes the BCD product of the values in registers _rs1_ and _rs2_ and places the result in register _rd_.

Mnemonic::
====
mulbcd _rd_, _rs1_, _rs2_

mulbcdw _rd_, _rs1_, _rs2_

====
Encoding::
TBD, somewhere in OP/OP64

Description::

Computes the BCD product of the values in registers _rs1_ and _rs2_ and places the result in register _rd_.
If either source operand is invalid, or the product overflows, the canonical invalid BCD value (0x0) is placed in register _rd_.
The word-sized version is RV64 only.

SAIL code::
[source,sail]
--
TODO
--

=== BCD Divide

Synopsis::
Computes the BCD sum of the values in registers _rs1_ and _rs2_ and places the result in register _rd_.

Mnemonic::
====
addbcd _rd_, _rs1_, _rs2_

addbcdw _rd_, _rs1_, _rs2_

====
Encoding::
TBD, somewhere in OP/OP64

Description::

Computes the BCD sum of the values in registers _rs1_ and _rs2_ and places the result in register _rd_.
If either source operand is invalid, or the sum overflows, the canonical invalid BCD value (0x0) is placed in register _rd_.
The word-sized version is RV64 only.

SAIL code::
[source,sail]
--
TODO
--
