[[intro]]
== Introduction

The purpose of this extension is to close a clear competitive gap of RISC-V: the lack of BCD instructions.
Unlike competing architectures such as System 360 and x86-32, RISC-V lacks efficient instructions for working with BCD data, and for converting it back and forth with other representations.
This proposal seeks to allievate that gap by proposing two groups of new instructions:


* BCD Arithmetic Instructions
* BCD Conversion Instructions

=== Representation

A packed BCD representation, where each digit is allocated 4 bits, is used in this extension.
To convert to and from zoned representations, bit packing instructions must be used (a nibble-wise zip/unzip).
BCD numbers are represented in the registers in a big-endian format, with the least-significant digit occupying bits [3:0].
Signed BCD is always used in this extension, with the high four bits of the register representing the sign.
0xC represents a '+' sign and 0xD represents a '-' sign.
Negative zeroes are valid source operands but will never be produced as destination operands.

The canonical representation for invalid BCD numbers is 0x0.
To avoid having traps on arithmetic operations, any BCD operation that has invalid sources (such as having digit nibbles out of the range 0x0-0x9, or an invalid sign nibble), or that would produce an invalid result, produces the canonical invalid BCD value.
0x0 is chosen for the canonical representation for ease of comparing against for branches to handle the error case.

As 32-bit values, the range of numbers that can be represented is from -9,999,999 to +9,999,999.
When stored in a 64-bit register, they are sign-extended from bit 31 as normal.
As 64-bit values, the range of numbers that can be represented is from -999,999,999,999,999 to 999,999,999,999,999.
